spring.application.name=platform-service

spring.jpa.open-in-view=false
spring.mvc.problemdetails.enabled=true

spring.security.oauth2.resourceserver.jwt.issuer-uri=${EOC_SECURITY_ISSUER_URI:http://localhost:8180/realms/eoc}
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${EOC_SECURITY_JWK_SET_URI:http://localhost:8180/realms/eoc/protocol/openid-connect/certs}
spring.security.oauth2.resourceserver.jwt.audiences=${EOC_SECURITY_AUDIENCE:platform-api}
