package io.github.khaledshawki.eoc.operations.application.model.reconciliation;

public enum ReceivableReconciliationIssue {
  INVOICE_CANCELLED_WITH_ACTIVE_ALLOCATIONS,
  INVOICE_ALLOCATION_CAPACITY_EXCEEDED,
  ALLOCATION_CURRENCY_MISMATCH,
  SETTLEMENT_CUSTOMER_MISMATCH,
  SETTLEMENT_CURRENCY_MISMATCH,
  PAYMENT_CUSTOMER_MISMATCH,
  PAYMENT_CURRENCY_MISMATCH,
  PAYMENT_REVERSED_WITH_ACTIVE_ALLOCATIONS,
  PAYMENT_ALLOCATION_CURRENCY_CONFLICT,
  PAYMENT_ALLOCATION_CAPACITY_EXCEEDED
}
